- hosts: localhost
  gather_facts: no
  remote_user: ubuntu
  become: yes
  #become_method: sudo
  tasks:

  - name: Remove all the containers
    shell: sudo docker rm -f $(docker ps -a -q)
    ignore_errors: yes
    become: yes
  
  - name: Remove all the ssh keys
    shell: mkdir -p /home/$(echo $USER)/.ssh
    shell: rm -f /home/$(echo $USER)/.ssh/known_hosts 
    ignore_errors: yes
      
##
##Create Topology
  - name: run set_vars_file.py
    script: "{{playbook_dir}}/scripts/set_vars_file.py"
   

  - name: read the vars_file
    include_vars:
      file: "{{playbook_dir}}/scripts/vars_file.yaml"
      name: names
   
  - name: spwan the containers 
    docker_container:
      image: quagga_image
      name: "{{item}}"
      state: started
      hostname: "{{item}}"
      privileged: yes
      interactive: yes
      tty: yes  
    with_items: 
      - "{{names.container_names}}"

  - name: Run Script
    script: "{{playbook_dir}}/scripts/connectivity_script.py"

##CronJob to monitor for updates
  - name: change file permissions
    file:
      path: "{{playbook_dir}}/scripts/monitor_config.py"
      mode: 0755

  - name: Running the monitor script in the background every 15 seconds
    cron:
      name: "run monitor script"
      minute: "*/1"
      hour: "*"
      day: "*"
      weekday: "*"
      month: "*"
      job: "{{playbook_dir}}/scripts/monitor_config.py"
